# Generated by Django 4.2 on 2024-12-07 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0002_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-created_on',)},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='msm',
            new_name='msg',
        ),
    ]
