# Generated by Django 4.2 on 2024-12-07 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0004_alter_comment_reply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='reply',
            new_name='parent',
        ),
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.FileField(default='comment-images/user.jpg', upload_to='comment-images/'),
        ),
    ]
